### ISSUE TITLE
deeplearning4j

### ISSUE THREAD

**Issue by vahed-p** [vahed-p/Vp#1]
hi
i am new to dl4j . I've been trying to run Shakespeare example. after doing all manual instructions and running the project i got errors. i am using Eclipse. i tried with different versions of dl4j, nd4j and datavec but it didn't work. with different version i got different error, here is the the error i got: 

Exception in thread "main" java.lang.AbstractMethodError: org.nd4j.linalg.api.ops.impl.transforms.strict.ACos.name()Ljava/lang/String;
	at org.nd4j.linalg.api.ops.factory.DefaultOpFactory.<init>(DefaultOpFactory.java:59)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5240)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5149)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:169)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:485)
	at tst.tst1.App.main(App.java:88)

**Comment by vahed-p** [comment]
here is the pom file: 

<project	xmlns="http://maven.apache.org/POM/4.0.0"
									xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
									xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
												http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>tst</groupId>
  <artifactId>tst1</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>tst1</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    	<nd4j.version>0.5..0</nd4j.version>
		<dl4j.version>0.5.0</dl4j.version>
		<datavec.version>0.5.0</datavec.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    
      <dependency>
					<groupId>org.nd4j</groupId>
					<artifactId>nd4j-api</artifactId>
					<version>0.5.0</version>
			</dependency>
			
    	   <dependency>
					<groupId>org.deeplearning4j</groupId>
					<artifactId>deeplearning4j-core</artifactId>
					<version>0.5.0</version>
		   </dependency>
		   
		   
			
			
			<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native-platform</artifactId>
    <version>0.5.0</version>
</dependency>

<dependency>
    <groupId>org.datavec</groupId>
    <artifactId>datavec-api</artifactId>
    <version>0.5.0</version>
</dependency>
      	    
      	    		
			
			
		  <dependency>
    		<groupId>org.bytedeco.javacpp-presets</groupId>
  			<artifactId>ffmpeg</artifactId>
    		<version>3.4.2-1.4.1</version>
		  </dependency>

         
    
    	  <dependency>
              <groupId>org.deeplearning4j</groupId>
              <artifactId>jumpy</artifactId>
              <version>1.0.0-beta6</version>
           </dependency>
           
          

		 
    
  </dependencies>
</project>

**Comment by vahed-p** [comment]
here is the pom file:

<project	xmlns="http://maven.apache.org/POM/4.0.0"
									xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
									xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
												http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>tst</groupId>
  <artifactId>tst1</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>tst1</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    	<nd4j.version>0.5..0</nd4j.version>
		<dl4j.version>0.5.0</dl4j.version>
		<datavec.version>0.5.0</datavec.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    
      <dependency>
					<groupId>org.nd4j</groupId>
					<artifactId>nd4j-api</artifactId>
					<version>0.5.0</version>
			</dependency>
			
    	   <dependency>
					<groupId>org.deeplearning4j</groupId>
					<artifactId>deeplearning4j-core</artifactId>
					<version>0.5.0</version>
		   </dependency>
		   
		   
			
			
			<dependency>
    <groupId>org.nd4j</groupId>
    <artifactId>nd4j-native-platform</artifactId>
    <version>0.5.0</version>
</dependency>

<dependency>
    <groupId>org.datavec</groupId>
    <artifactId>datavec-api</artifactId>
    <version>0.5.0</version>
</dependency>
      	    
      	    		
			
			
		  <dependency>
    		<groupId>org.bytedeco.javacpp-presets</groupId>
  			<artifactId>ffmpeg</artifactId>
    		<version>3.4.2-1.4.1</version>
		  </dependency>

         
    
    	  <dependency>
              <groupId>org.deeplearning4j</groupId>
              <artifactId>jumpy</artifactId>
              <version>1.0.0-beta6</version>
           </dependency>
           
          

		 
    
  </dependencies>
</project>

**Comment by vahed-p** [comment]
this is the my pom file:

[New Text Document.txt](https://github.com/vahed-p/Vp/files/4350721/New.Text.Document.txt)
